### ISSUE TITLE
Erro redirecionamento ambíguo no script

### ISSUE THREAD

**Issue by JosarAlves** [xalalau/Instalator#1]
cara eu tentei usar o seu script do instaletor e deu o seguinte bug:
❱ winetricks                                                               /home/jos/Instaleytor/include/funcoes.sh: linha 161: $CONSOLE: redirecionamento ambíguo
/home/jos/Instaleytor/include/funcoes.sh: linha 162: $CONSOLE: redirecionamento ambíguo

Esse erro deu em todos os programas do script inteiro. O que poderia estar causando isso.

**Comment by JosarAlves** [comment]
dei permissão de execução para o arquivo newterm.sh e funcionou de boa

**Comment by Xalalau** [comment]
É o que eu ia dizer, tem que dar permissão para todos os .sh. Eu tenho que acabar com isso...

**Comment by JosarAlves** [comment]
Era bom colocar nas instruçoes pra dar as permissões a todos. Fora isso o
instaleytor ta otimo e muiti util, ja vou usar da proxima vez que eu
formatar o pc. Mas me diga um coisa ai, ele tambem instala snap e flatpak?
Se nao tem como fazer instalar


Em dom, 15 de dez de 2019 3:50 AM, Xalalau Xubilozo <
notifications@github.com> escreveu:

**Comment by Xalalau** [comment]
Ele não instala porque eu não escrevi o suporte, já q tinha dúvidas de qual formato valia a pena e q eu não uso eles praticamente. Hoje já sei que tem que ter os dois, falta é tempo pra fazer isso. Adicionei no to-do.

**Comment by JosarAlves** [comment]
Mas o instalador ta muito completo. Parabéns.


Em dom, 15 de dez de 2019 10:53 AM, Xalalau Xubilozo <
notifications@github.com> escreveu:

**Comment by Xalalau** [comment]
Obrigado!

Vou alterar o script pra fazer essas coisas quando eu terminar de atualizar minhas ferramentas do Garry's Mod.

Qualquer problema ou dúvida, posta aí. Amo quando alguém usa algo q eu criei.

Vlw!

**Comment by JosarAlves** [comment]
É sempre bom elogiar quando alguém algo bem feito. Eu usei o codigo no
ubuntu gnome e no kubuntu, ambos na versao 18.04.3. Pelo que vi so alguns
programas, sendo esses dropbox, java, wine e o appimagelauncher.

Outra coisa que vale dizer é que o gimp instalado via repositorio vem
desatualizado na versao 2.8 por isso eram bom ter o flatpak.
Fora isso nao notei nenhum problema, se eu encontrar alguma coisa aviso.

Em dom, 15 de dez de 2019 10:21 PM, Xalalau Xubilozo <
notifications@github.com> escreveu:

**Comment by Xalalau** [comment]
Ué, vc tá usando a minha lista? Faz a sua, poxa... Esse que é o ponto do script.

Mas não tem problema que uma coisa ou outra não instale ao mudar de sistema, isso é só alteração de nome de pacotes ou indisponibilidade de suporte de um repositório. O importante é que as funções funcionam corretamente e entregam o resultado depois de se ajustar os programas.

De qlqr forma, curti mto os seus testes! Eu tava esperando que vc fosse atualizar uma vez o seu sistema, mas vc tá é fazendo um tipo de distro hopping. Show.

**Comment by JosarAlves** [comment]
Na verdade eu tava querendo testar o ubuntu gnome e resolvi testa o seu
codigo. Mas pra fazer minha lista fica difícil, nao entendo nada de shell
script e tenho medo de bigar os comandos.

Em seg, 16 de dez de 2019 10:59 PM, Xalalau Xubilozo <
notifications@github.com> escreveu:

**Comment by JosarAlves** [comment]
Fora que a sua lista ta bem completa e serve ate pra descobri novos
programas tipp hamachi que eu nao fazia ideia que tinha versao pra linux


Em seg, 16 de dez de 2019 11:12 PM, Josar Alves <josaralves9@gmail.com>
escreveu:

**Comment by Xalalau** [comment]
Não precisa saber shell, é só editar a lista mesmo https://github.com/Xalalau/Instaleytor/blob/master/include/entrada.sh

Deleta linha, adiciona... Done

**Comment by JosarAlves** [comment]
Vou tentar adcionar umas coisas mas so da proxima vez que eu precisar agora
ja instalei no meu pc

Em seg, 16 de dez de 2019 11:39 PM, Xalalau Xubilozo <
notifications@github.com> escreveu:

**Comment by Xalalau** [comment]
Pelo menos checa ela pra saber tudo q tem.

Por exemplo, abre o terminal e digita neofetch. Vc instalou isso Kkkk

**Comment by JosarAlves** [comment]
Pelo neofetch diz que tem 2873 pacotes dpkg 6 flatpak e 3 snap


Em seg, 16 de dez de 2019 11:43 PM, Xalalau Xubilozo <
notifications@github.com> escreveu:

**Comment by JosarAlves** [comment]
Ei cara me diga uma coisa. O arquivo ttyecho precisa de permissao de
executavel tb?

Em qua, 18 de dez de 2019 7:35 PM, Josar Alves <josaralves9@gmail.com>
escreveu:

**Comment by Xalalau** [comment]
Não. Esse arquivo é para compilar o programa que envia saídas de um terminal para o outro, o que permite termos duas janelas. Só usamos ele quando o executável incluso não funciona e precisamos de um novo, isso não requer mudança de permissões.

**Comment by JosarAlves** [comment]
Vlw brother.

Em dom, 22 de dez de 2019 11:18 AM, Xalalau Xubilozo <
notifications@github.com> escreveu:
